default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: underflow_development
  username: underflow
  password: 123

test:
  <<: *default
  database: underflow_test
  username: underflow
  password: 123

production:
  <<: *default
  database: underflow_production
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>
