development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: underflow.riabit.ru
  secret_token: 2d7ab81b1ff737db346b2093f30ce36b6c6947d5b975928467438
  signature_expiration: 3600 # one hour
