development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: <%= Rails.application.secrets.private_pub_host %>
  secret_token: <%= Rails.application.secrets.private_pub_secret %>
  signature_expiration: 3600 # one hour
